# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - 3.5.0
  - oldrel
  - release
  - devel

# set environment variables
TRAVIS_R_VERSION=3.5.0 Set to version chosen by r:.
R_LIBS_USER=~/R/Library
R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library
_R_CHECK_CRAN_INCOMING_=false
NOT_CRAN=true
R_PROFILE=~/.Rprofile.site

# Install R packages
  - "./travis-tool.sh r_binary_install odbc DBI"
